import { Document, Packer, Paragraph, HeadingLevel, TextRun } from 'docx';
import { OutputData } from '@/types';

export async function generateDocx(
  title: string,
  output: OutputData
): Promise<Buffer> {
  const paragraphs: Paragraph[] = [
    new Paragraph({
      text: title,
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 },
    }),
  ];

  for (const section of output.sections) {
    paragraphs.push(
      new Paragraph({
        text: section.title,
        heading: HeadingLevel.HEADING_2,
        spacing: { after: 100, before: 100 },
      })
    );

    const contentParagraphs = section.content
      .split('\n')
      .filter((line) => line.trim())
      .map(
        (line) =>
          new Paragraph({
            text: line,
            spacing: { line: 360, after: 100 },
          })
      );

    paragraphs.push(...contentParagraphs);
  }

  paragraphs.push(
    new Paragraph({
      text: 'Generated by Agentic Author',
      spacing: { before: 400 },
      alignment: 'center' as any,
      run: new TextRun({
        italics: true,
        size: 18,
      }),
    })
  );

  const doc = new Document({
    sections: [
      {
        children: paragraphs,
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  return buffer;
}
