import PDFDocument from 'pdfkit';
import { OutputData } from '@/types';

export function generatePdf(title: string, output: OutputData): Buffer {
  const doc = new PDFDocument({
    margin: 50,
  });

  const chunks: Buffer[] = [];

  doc.on('data', (chunk: Buffer) => {
    chunks.push(chunk);
  });

  // Title page
  doc.fontSize(28).font('Helvetica-Bold').text(title, { align: 'center' });
  doc.moveDown(2);
  doc.fontSize(12)
    .font('Helvetica')
    .text(`Generated by Agentic Author`, { align: 'center' });
  doc.moveDown(1);
  doc.fontSize(10)
    .font('Helvetica')
    .text(`Generated on ${new Date().toLocaleDateString()}`, { align: 'center' });

  doc.addPage();

  let pageNumber = 2;

  for (const section of output.sections) {
    doc.fontSize(16).font('Helvetica-Bold').text(section.title);
    doc.moveDown(0.5);

    doc.fontSize(11).font('Helvetica');

    const lines = section.content.split('\n');
    for (const line of lines) {
      if (line.trim()) {
        doc.text(line, { align: 'left' });
      } else {
        doc.moveDown(0.5);
      }
    }

    doc.moveDown(1);

    const pageHeight = doc.page.height;
    const currentY = doc.y;
    if (currentY > pageHeight - 100) {
      doc.addPage();
      pageNumber++;
    }
  }

  // Add page numbers
  const pages = doc.bufferedPageRange().count;
  for (let i = 0; i < pages; i++) {
    doc.switchToPage(i);
    doc.fontSize(10)
      .font('Helvetica')
      .text(`Page ${i + 1} of ${pages}`, 50, doc.page.height - 50, {
        align: 'center',
      });
  }

  doc.end();

  return Buffer.concat(chunks);
}
