'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { WizardShell } from '@/components/wizard/WizardShell';
import { useWizardStore } from '@/store/wizard.store';
import { useToast } from '@/components/ui/use-toast';

export default function NewProjectPage() {
  const router = useRouter();
  const { toast } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);
  
  const resetWizard = useWizardStore(state => state.resetWizard);
  const answers = useWizardStore(state => state.answers);
  const category = useWizardStore(state => state.category);
  const generatedPrompt = useWizardStore(state => state.generatedPrompt);

  useEffect(() => {
    // Clean up wizard state on mount and unmount
    resetWizard();
    return () => resetWizard();
  }, [resetWizard]);

  const handleComplete = async () => {
    if (!answers.title || !category || !generatedPrompt) {
      toast({
        title: 'Missing information',
        description: 'Please ensure all required fields and prompt are filled.',
        variant: 'destructive',
      });
      return;
    }

    setIsSubmitting(true);

    console.log('Submitting:', {
      title: answers.title,
      category,
      rawPromptLength: generatedPrompt.length,
    });

    try {
      // 1. Create the project
      const createRes = await fetch('/api/projects', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: answers.title,
          category,
          rawPrompt: generatedPrompt,
        }),
      });

      if (!createRes.ok) {
        const errorData = await createRes.json();
        console.error('Project creation error:', errorData);
        throw new Error(errorData.error || 'Failed to create project');
      }

      const project = await createRes.json();

      // 2. Trigger the pipeline
      const runRes = await fetch('/api/pipeline/run', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          projectId: project._id,
        }),
      });

      if (!runRes.ok) {
        const errorData = await runRes.json();
        console.error('Pipeline run error:', errorData);
        throw new Error(errorData.error || 'Failed to start pipeline');
      }

      // 3. Navigate to the project page
      toast({
        title: 'Project Created',
        description: 'Your project is now being generated by the AI pipeline.',
      });
      
      router.push(`/projects/${project._id}`);

    } catch (error) {
      toast({
        title: 'Error',
        description: error instanceof Error ? error.message : 'An unexpected error occurred.',
        variant: 'destructive',
      });
      setIsSubmitting(false);
    }
  };

  return (
    <div className="flex min-h-[calc(100vh-8rem)] flex-col items-center justify-center py-10">
      <div className="mb-8 text-center">
        <h1 className="font-sora text-3xl font-bold text-zinc-100">Create a New Project</h1>
        <p className="mt-2 text-zinc-400">Let the AI help you craft the perfect prompt.</p>
      </div>

      <WizardShell 
        onComplete={handleComplete} 
        isSubmitting={isSubmitting} 
      />
    </div>
  );
}
