import { CategoryConfig, ContentCategory } from '@/types';

export const CATEGORY_CONFIG: Record<ContentCategory, CategoryConfig> = {
  book: {
    label: 'Book / Novel',
    icon: '📚',
    description: 'Fiction or non-fiction books with full chapter structure',
    planStructure: ['premise', 'characters', 'world_building', 'chapters'],
    writingStyle: 'narrative-engaging',
    researchDepth: 'moderate',
    citationRequired: false,
    maxWordsPerTier: { free: 3000, pro: 50000 },
  },
  screenplay: {
    label: 'Screenplay / Script',
    icon: '🎬',
    description: 'Feature films, short films, or TV pilot scripts',
    planStructure: ['logline', 'act_one', 'act_two', 'act_three', 'scenes'],
    writingStyle: 'screenplay-format',
    researchDepth: 'light',
    citationRequired: false,
    maxWordsPerTier: { free: 2000, pro: 30000 },
  },
  thesis: {
    label: 'Academic Thesis',
    icon: '🎓',
    description: 'Undergraduate, Masters, or PhD thesis with citations',
    planStructure: [
      'abstract',
      'introduction',
      'literature_review',
      'methodology',
      'results',
      'discussion',
      'conclusion',
      'references',
    ],
    writingStyle: 'academic-formal',
    researchDepth: 'deep',
    citationRequired: true,
    maxWordsPerTier: { free: 3000, pro: 60000 },
  },
  journal: {
    label: 'Journal Article',
    icon: '📰',
    description: 'Peer-reviewed academic articles with structured format',
    planStructure: [
      'abstract',
      'introduction',
      'methods',
      'results',
      'discussion',
      'references',
    ],
    writingStyle: 'academic-concise',
    researchDepth: 'deep',
    citationRequired: true,
    maxWordsPerTier: { free: 2000, pro: 15000 },
  },
  educational: {
    label: 'Educational Content',
    icon: '🏫',
    description: 'Lesson plans, course modules, and study guides',
    planStructure: ['objectives', 'overview', 'modules', 'activities', 'assessments'],
    writingStyle: 'instructional-clear',
    researchDepth: 'moderate',
    citationRequired: false,
    maxWordsPerTier: { free: 2000, pro: 20000 },
  },
  article: {
    label: 'Blog Article / Post',
    icon: '📝',
    description: 'Engaging blog posts, news articles, and web content',
    planStructure: ['introduction', 'body_paragraph_one', 'body_paragraph_two', 'body_paragraph_three', 'conclusion'],
    writingStyle: 'conversational-informative',
    researchDepth: 'moderate',
    citationRequired: true,
    maxWordsPerTier: { free: 1500, pro: 10000 },
  },
  social_media: {
    label: 'Social Media Content',
    icon: '📱',
    description: 'Twitter threads, LinkedIn posts, and Instagram captions',
    planStructure: ['hook', 'context', 'value_points', 'call_to_action'],
    writingStyle: 'punchy-persuasive',
    researchDepth: 'light',
    citationRequired: false,
    maxWordsPerTier: { free: 500, pro: 5000 },
  },
};
